# Generated by Django 2.2.4 on 2019-09-10 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('type', models.CharField(max_length=45)),
                ('status', models.CharField(max_length=45)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=500)),
                ('geo_lat', models.FloatField(blank=True, null=True)),
                ('geo_lng', models.FloatField(blank=True, null=True)),
                ('logo', models.CharField(max_length=255)),
                ('ecobuilder_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Organization')),
            ],
        ),
    ]
