# Generated by Django 2.2.4 on 2019-09-11 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # migrations.CreateModel(
        #     name='IntCompany',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('name', models.CharField(max_length=150)),
        #         ('class_field', models.CharField(blank=True, db_column='class', max_length=100, null=True)),
        #         ('description', models.CharField(blank=True, max_length=200, null=True)),
        #     ],
        #     options={
        #         'db_table': 'int_company',
        #     },
        # ),
        # migrations.CreateModel(
        #     name='IntGroup',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('name', models.CharField(max_length=150)),
        #     ],
        #     options={
        #         'db_table': 'int_group',
        #     },
        # ),
        # migrations.CreateModel(
        #     name='IntInfluencer',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('name', models.CharField(max_length=150)),
        #     ],
        #     options={
        #         'db_table': 'int_influencer',
        #     },
        # ),
        # migrations.CreateModel(
        #     name='IntSchool',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('name', models.CharField(max_length=150)),
        #     ],
        #     options={
        #         'db_table': 'int_school',
        #     },
        # ),
        # migrations.CreateModel(
        #     name='Organization',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('name', models.CharField(max_length=150)),
        #         ('type', models.CharField(blank=True, max_length=45, null=True)),
        #         ('status', models.CharField(blank=True, max_length=45, null=True)),
        #         ('description', models.TextField(blank=True, null=True)),
        #         ('address', models.CharField(blank=True, max_length=500, null=True)),
        #         ('geo_lat', models.FloatField(blank=True, null=True)),
        #         ('geo_lng', models.FloatField(blank=True, null=True)),
        #         ('logo', models.CharField(blank=True, max_length=256, null=True)),
        #         ('ecobuilder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Organization')),
        #     ],
        #     options={
        #         'db_table': 'organization',
        #     },
        # ),
        # migrations.CreateModel(
        #     name='Person',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('name', models.CharField(max_length=45)),
        #         ('job_present', models.CharField(blank=True, max_length=500, null=True)),
        #         ('job_present_org', models.CharField(blank=True, max_length=300, null=True)),
        #         ('description', models.TextField(blank=True, null=True)),
        #         ('organization_id', models.IntegerField()),
        #         ('linkedin', models.CharField(max_length=255)),
        #         ('lattes', models.CharField(max_length=255)),
        #         ('higher_education', models.IntegerField()),
        #     ],
        #     options={
        #         'db_table': 'person',
        #     },
        # ),
        # migrations.CreateModel(
        #     name='ResearchArea',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('group', models.CharField(max_length=100)),
        #         ('class_field', models.CharField(db_column='class', max_length=100)),
        #         ('sub_class', models.CharField(blank=True, max_length=100, null=True)),
        #     ],
        #     options={
        #         'db_table': 'research_area',
        #     },
        # ),
        # migrations.CreateModel(
        #     name='Sector',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('name', models.CharField(max_length=45)),
        #     ],
        #     options={
        #         'db_table': 'sector',
        #     },
        # ),
        # migrations.CreateModel(
        #     name='SkillClass',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('name', models.CharField(max_length=255)),
        #     ],
        #     options={
        #         'db_table': 'skill_class',
        #     },
        # ),
        # migrations.CreateModel(
        #     name='Skill',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('name', models.CharField(max_length=300)),
        #         ('class_field', models.CharField(blank=True, db_column='class', max_length=45, null=True)),
        #         ('skill_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.SkillClass')),
        #     ],
        #     options={
        #         'db_table': 'skill',
        #     },
        # ),
        # migrations.CreateModel(
        #     name='Education',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('title', models.CharField(max_length=45)),
        #         ('institution', models.CharField(max_length=200)),
        #         ('year_start', models.IntegerField()),
        #         ('year_end', models.IntegerField(blank=True, null=True)),
        #         ('month_start', models.IntegerField(blank=True, null=True)),
        #         ('month_end', models.IntegerField(blank=True, null=True)),
        #         ('description', models.TextField(blank=True, null=True)),
        #         ('weight', models.IntegerField(blank=True, null=True)),
        #         ('person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Person')),
        #         ('research_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.ResearchArea')),
        #     ],
        #     options={
        #         'db_table': 'education',
        #     },
        # ),
        # migrations.CreateModel(
        #     name='Friend',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('qtd', models.IntegerField(default=0)),
        #         ('friend', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='friend_person_friend', to='core.Person')),
        #         ('person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='friend_person_person', to='core.Person')),
        #     ],
        #     options={
        #         'db_table': 'friend',
        #         'unique_together': {('person', 'friend')},
        #     },
        # ),
        # migrations.CreateModel(
        #     name='Experience',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('role', models.CharField(max_length=150)),
        #         ('organization', models.CharField(max_length=150)),
        #         ('year_start', models.IntegerField(blank=True, null=True)),
        #         ('year_end', models.IntegerField(blank=True, null=True)),
        #         ('month_start', models.IntegerField(blank=True, null=True)),
        #         ('month_end', models.IntegerField(blank=True, null=True)),
        #         ('description', models.TextField(blank=True, null=True)),
        #         ('person_organization_id', models.IntegerField()),
        #         ('location', models.CharField(blank=True, max_length=300, null=True)),
        #         ('person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Person')),
        #     ],
        #     options={
        #         'db_table': 'experience',
        #         'unique_together': {('id', 'person', 'person_organization_id')},
        #     },
        # ),
        # migrations.CreateModel(
        #     name='Activity',
        #     fields=[
        #         ('id', models.IntegerField(primary_key=True, serialize=False)),
        #         ('action', models.CharField(blank=True, max_length=45, null=True)),
        #         ('friend_name', models.CharField(blank=True, max_length=200, null=True)),
        #         ('friend_linkedin_url', models.CharField(blank=True, db_column='friend_linkedIn_url', max_length=255, null=True)),
        #         ('description', models.TextField(blank=True, null=True)),
        #         ('person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Person')),
        #     ],
        #     options={
        #         'db_table': 'activity',
        #         'unique_together': {('id', 'person')},
        #     },
        # ),
        # migrations.CreateModel(
        #     name='PersonIntSchool',
        #     fields=[
        #         ('person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.Person')),
        #         ('int_school', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.IntSchool')),
        #     ],
        #     options={
        #         'db_table': 'person_int_school',
        #         'unique_together': {('person', 'int_school')},
        #     },
        # ),
        # migrations.CreateModel(
        #     name='PersonIntInfluencer',
        #     fields=[
        #         ('person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.Person')),
        #         ('int_influencer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.IntInfluencer')),
        #     ],
        #     options={
        #         'db_table': 'person_int_influencer',
        #         'unique_together': {('person', 'int_influencer')},
        #     },
        # ),
        # migrations.CreateModel(
        #     name='PersonIntGroup',
        #     fields=[
        #         ('person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.Person')),
        #         ('int_group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.IntGroup')),
        #     ],
        #     options={
        #         'db_table': 'person_int_group',
        #         'unique_together': {('person', 'int_group')},
        #     },
        # ),
        # migrations.CreateModel(
        #     name='PersonIntCompany',
        #     fields=[
        #         ('person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.Person')),
        #         ('int_company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.IntCompany')),
        #     ],
        #     options={
        #         'db_table': 'person_int_company',
        #         'unique_together': {('person', 'int_company')},
        #     },
        # ),
        # migrations.CreateModel(
        #     name='PersonHasSkill',
        #     fields=[
        #         ('person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.Person')),
        #         ('qtd', models.IntegerField()),
        #         ('skill', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Skill')),
        #     ],
        #     options={
        #         'db_table': 'person_has_skill',
        #         'unique_together': {('person', 'skill')},
        #     },
        # ),
        # migrations.CreateModel(
        #     name='OrgHasSector',
        #     fields=[
        #         ('organization', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.Organization')),
        #         ('sector', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Sector')),
        #     ],
        #     options={
        #         'db_table': 'org_has_sector',
        #         'unique_together': {('organization', 'sector')},
        #     },
        # ),
        # migrations.CreateModel(
        #     name='OrgHasPerson',
        #     fields=[
        #         ('organization', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, unique=True, serialize=False, to='core.Organization')),
        #         ('function', models.CharField(blank=True, max_length=255, null=True)),
        #         ('description', models.TextField(blank=True, null=True)),
        #         ('year_start', models.IntegerField(blank=True, null=True)),
        #         ('year_end', models.IntegerField(blank=True, null=True)),
        #         ('month_start', models.IntegerField(blank=True, null=True)),
        #         ('month_end', models.IntegerField(blank=True, null=True)),
        #         ('person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Person')),
        #     ],
        #     options={
        #         'db_table': 'org_has_person',
        #         'unique_together': {('organization', 'person')},
        #     },
        # ),
    ]
