# Generated by Django 2.2.4 on 2019-09-17 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='User',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('username', models.CharField(max_length=45, unique=True)),
        #         ('password', models.CharField(max_length=50)),
        #         ('email', models.CharField(max_length=500)),
        #         ('profile', models.CharField(max_length=45)),
        #         ('avatar', models.CharField(blank=True, max_length=256, null=True)),
        #         ('person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Person')),
        #     ],
        #     options={
        #         'db_table': 'user',
        #         'unique_together': {('id', 'person')},
        #     },
        # ),
    ]
